describe('Calculator', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000')
  })

  it('should have working number buttons', () => {
    cy.get('#number2').click()
    cy.get('.display').should('contain', '2')
  })

  it('the number buttons should update the display', () => {
    cy.get('#number2').click()
    cy.get('#number5').click()
    cy.get('#number6').click()
    cy.get('#number9').click()
    cy.get('#operator-multiply').click()
    cy.get('#number2').click()
    cy.get('#operator-equals').click()
    cy.get('.display').should('contain', '5138')
  })
  it('can chain multiple operations', () => {
    cy.get('#number2').click()
    cy.get('#operator-multiply').click()
    cy.get('#number5').click()
    cy.get('#operator-equals').click()
    cy.get('#operator-subtract').click()
    cy.get('#number6').click()
    cy.get('#operator-equals').click()
    cy.get('.display').should('contain', '4')
  })
  it('can output a positive number', () => {
    cy.get('#number2').click()
    cy.get('#operator-multiply').click()
    cy.get('#number5').click()
    cy.get('#operator-equals').click()
    cy.get('.display').should('contain', '10')
  })
  it('can output a negative number', () => {
    cy.get('#number5').click()
    cy.get('#operator-subtract').click()
    cy.get('#number9').click()
    cy.get('#operator-equals').click()
    cy.get('.display').should('contain', '-4')
  })
  it('can output a decimal number', () => {
    cy.get('#number5').click()
    cy.get('#operator-divide').click()
    cy.get('#number2').click()
    cy.get('#operator-equals').click()
    cy.get('.display').should('contain', '2.5')
  })
   it('can output a large number', () => {
     cy.get('#number5').click()
     cy.get('#number5').click()
     cy.get('#number5').click()
     cy.get('#number5').click()
     cy.get('#number5').click()
     cy.get('#number5').click()
     cy.get('#number5').click()
     cy.get('#number5').click()
     cy.get('#number5').click()
     cy.get('#number5').click()
     cy.get('#number5').click()
     cy.get('#operator-multiply').click()
     cy.get('#number2').click()
     cy.get('#operator-equals').click()
     cy.get('.display').should('contain', '111111111110')
   })
   it('can divide by zero', () => {
     cy.get('#number5').click()
     cy.get('#operator-divide').click()
     cy.get('#number0').click()
     cy.get('#operator-equals').click()
     cy.get('.display').should('contain', 'error')
   })
})
